### PR TITLE
build: use whiskers

### PR DESCRIPTION
**Pull request by uncenter**
Adds [Whiskers](https://github.com/catppuccin/toolbox/tree/main/whiskers), Catppuccin's internal templating tool, to build the themes. Instead of editing the `.toml` files directly, edit the `starship.tera` file and then run `just build` to build the output themes (though this shouldn't need to happen much as the theme files are just loops over the palette colors). You will need Whiskers (linked above) and *optionally* [Just](https://github.com/casey/just) installed. I've also updated the usage instructions.

~~Draft until https://github.com/catppuccin/toolbox/pull/217 is merged so that the suggested/example starship.toml configuration can pull from the generated palettes.~~

### CODE REVIEW

**Comment by JoshPaulie** [comment]
You beat me to it!

Very cool. Thanks 👍

**Comment by uncenter** [comment]
Should be good to go @JoshPaulie :)

**Review by sgoudham — APPROVED** [review]
@JoshPaulie Are you happy to merge this? It looks good to me :+1:

**Comment by JoshPaulie** [comment]
Omg! So sorry. I thought I merged this ages ago. Thanks for whipping this together!

**Comment by injust** [comment]
I think this somehow messed up the README? [`themes/`](https://github.com/catppuccin/starship/blob/main/themes) in the [Usage section](https://github.com/catppuccin/starship/blob/main/README.md#usage) is a 404.

**Comment by sgoudham** [comment]
Oh good catch, haha the PR no longer looks good to me 😄 @injust 

The whiskers template moves the themes to `palettes` and not `themes`.

**Comment by sgoudham** [comment]
I somehow fat fingered committing to main instead of a new branch on GitHub mobile 🤦 

It's fixed on main now but I meant to say that a future PR might want to edit the directory to be `themes`.

**Comment by uncenter** [comment]
I think fixing the directory link was the wrong solution ahah, we want them in `themes` anyway.

**Pull request merged**
